sudo: required

notifications:
  email:
    recipients:
      - juan.baranowa@gmail.com
    on_success: never
    on_failure: always

branches:
  only:
  - master
  - feature/start

language: node_js

node_js:
 - "8"

services:
  - docker

before_install:
  - docker pull trufflesuite/ganache-cli
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest -h 0.0.0.0

install:
  - npm install -g truffle@4.1.15
  - npm install -g coveralls
  - npm install

#script:
  #- npm run solhint && npm test

after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls
